trigger:
  branches:
    include:
      - main

variables:
  imageName: askmycv

stages:
- stage: Build
  displayName: Build & Push Docker Image
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push image
      inputs:
        command: buildAndPush
        repository: $(imageName)
        dockerfile: '**/Dockerfile'
        containerRegistry: 'azure-aks-connection'
        tags: latest

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Kubernetes@1
      displayName: Deploy to AKS
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'azure-aks-connection'
        azureResourceGroup: 'pocs_abozar_simone_rg'
        kubernetesCluster: 'k8s-cluster'
        namespace: 'default'
        command: apply
        useConfigurationFile: true
        configuration: |
          k8s/askmycv-deployment.yaml
          k8s/askmycv-service.yaml
          k8s/askmycv-ingress.yaml
