trigger:
  branches:
    include:
      - main

variables:
  imageName: askmycv

stages:
- stage: Build
  displayName: Build & Push Docker Image
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push image
      inputs:
        command: buildAndPush
        repository: $(imageName)
        dockerfile: '**/Dockerfile'
        containerRegistry: 'simoneacr-connection'
        tags: latest

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: Build
  jobs:
    - job: Deploy
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - script: ls -lR
          displayName: "Elenca tutti i file"
        - task: AzureCLI@2
          displayName: 'Kubectl apply manifests'
          inputs:
            azureSubscription: 'azure-aks-arm-connection'   # Nome della Service Connection ARM!
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az aks get-credentials --resource-group pocs_abozar_simone_rg --name k8s-cluster --admin --overwrite-existing
              kubectl apply -f kubernetes/askmycv-deployment.yaml
              kubectl apply -f kubernetes/askmycv-service.yaml
              kubectl apply -f kubernetes/askmycv-ingress.yaml

